#ifndef _SUMMA_DMA_H_
#define _SUMMA_DMA_H_

#include "flex_dma_pattern.h"
#include "gemm_setup.h"

// Include address definitions
// preload.h: generated by gemm_preload.py (old preload workflow)
// gemm_data.h: generated by gemm_data_generator.py (new linker script workflow)
// Both define the same address macros (X_ADDR, W_ADDR, Z_EADDR, Z_GADDR, VQ_*_ADDR)
#include "gemm_addresses.h"
#include "spatz_rvv_extensions.h"
#include "vq_debug.h"
static inline void initZBuffer(const SummaGEMMInfo* info) {
    // Initialize Z buffer
    if (flex_is_dm_core()) {

        flex_dma_async_1d(info->L1_Z1, zomem(0), info->L1_Z_size);
        flex_dma_async_1d(info->L1_Z2, zomem(0), info->L1_Z_size);
        flex_dma_async_wait_all();
    }
    flex_intra_cluster_sync();
}

static inline void summa_load_X_tile(const SummaGEMMInfo* info, uint32_t dst_L1_X, int m, int n, int k) {
#if GEMM_RESHA_X_FROM_ENABLE == 1
    uint64_t mapped_offset = summa_compute_reshaped_X_offset(info, m, n, k);
    flex_dma_async_2d(dst_L1_X, info->X_tile_base + mapped_offset, info->K_tile * DATA_TYPE_BYTE,
                      info->K_tile * DATA_TYPE_BYTE, GEMM_RESHAPE_X_FROM_K * DATA_TYPE_BYTE, info->M_tile);
#else
    uint64_t base = (uint64_t)m * info->X_tile_M_iter_offset + (uint64_t)n * info->X_tile_N_iter_offset +
                    (uint64_t)k * info->X_tile_K_iter_offset;
    flex_dma_async_2d(dst_L1_X, info->X_tile_base + base, info->K_tile * DATA_TYPE_BYTE, info->K_tile * DATA_TYPE_BYTE,
                      info->K_size * DATA_TYPE_BYTE, info->M_tile);
#endif
    flex_dma_async_wait_all();

    if (info->summa_group_x > 1) {
        flex_dma_async_broadcast(dst_L1_X, dst_L1_X, info->L1_X_size, info->group.wakeup_row_mask,
                                 (ARCH_NUM_CLUSTER_Y - 1));
        flex_dma_async_wait_all();
    }
}

static inline void summa_load_W_tile(const SummaGEMMInfo* info, uint32_t dst_L1_W, int m, int n, int k) {
    flex_dma_async_2d(dst_L1_W, /*destination*/
                      info->W_tile_base + m * info->W_tile_M_iter_offset + n * info->W_tile_N_iter_offset +
                          k * info->W_tile_K_iter_offset, /*source*/
                      info->N_tile * DATA_TYPE_BYTE,      /*transfer size*/
                      info->N_tile * DATA_TYPE_BYTE,      /*destination stride*/
                      info->N_size * DATA_TYPE_BYTE,      /*source stride*/
                      info->K_tile /*repeat*/);           // Start 2D iDMA
    flex_dma_async_wait_all();                            // Wait for iDMA Finishing
    // col-wise multicast
    if (info->summa_group_y > 1) {
        flex_dma_async_broadcast(dst_L1_W /*dst_offset*/, dst_L1_W /*src_offset*/, info->L1_W_size /*transfer_size*/,
                                 (ARCH_NUM_CLUSTER_X - 1) /*row_mask*/, info->group.wakeup_col_mask /*col_mask*/);
        flex_dma_async_wait_all(); // Wait for iDMA Finishing
    }
}
static inline void summa_reduce_and_store_Z(SummaGEMMInfo* info, uint32_t DMA_L1_Z, bool clear) {
    if (info->group_reduction == 1) {
        flex_dma_async_reduction(DMA_L1_Z, DMA_L1_Z, info->L1_Z_size, COLLECTIVE_REDSUM_TYPE,
                                 ~info->group.wakeup_row_mask, ~info->group.wakeup_col_mask);
        flex_dma_async_wait_all();
    }

#if GEMM_RESHA_Z_TO_ENABLE == 1
    uint64_t mapped_offset = summa_compute_reshaped_Z_offset(info, info->store_m, info->store_n);

    flex_dma_async_2d(info->Z_tile_base + mapped_offset, DMA_L1_Z, info->N_tile * DATA_TYPE_BYTE,
                      GEMM_RESHAPE_Z_TO_N * DATA_TYPE_BYTE, info->N_tile * DATA_TYPE_BYTE, info->M_tile);
#else
    uint64_t base =
        (uint64_t)info->store_m * info->Z_tile_M_iter_offset + (uint64_t)info->store_n * info->Z_tile_N_iter_offset;

    flex_dma_async_2d(info->Z_tile_base + base, DMA_L1_Z, info->N_tile * DATA_TYPE_BYTE, info->N_size * DATA_TYPE_BYTE,
                      info->N_tile * DATA_TYPE_BYTE, info->M_tile);
#endif
    flex_dma_async_wait_all();
    if (clear) {
        // Clear Z buffer for reuse
        flex_dma_async_1d(DMA_L1_Z, zomem(0), info->L1_Z_size);
        flex_dma_async_wait_all();
        /* code */
    }
}
#if VQ_ENABLED == 1
static inline void vq_load_cb(SummaGEMMInfo* info) {

    if (flex_is_dm_core()) {
        for (int i = 0; i < VQ_NUM_CBS; ++i) {
            // Full load
            flex_dma_async_1d((uint64_t)info->vq.L1_CB[i], info->vq.VQ_CB_address[i], info->vq.L1_CB_size);
            flex_dma_async_wait_all();
        }

        for (int i = 0; i < VQ_NUM_CBS; ++i) {
            flex_dma_async_broadcast(info->vq.L1_CB[i], info->vq.L1_CB[i], info->vq.L1_CB_size,
                                     (ARCH_NUM_CLUSTER_X - 1) /*row_mask*/, info->group.wakeup_col_mask /*col_mask*/);
            flex_dma_async_wait_all();
        }
    }
}

static inline void summa_vq_load_scales(SummaGEMMInfo* info, uint32_t dst_L1_Scales, int m, int n, int k) {
    // Calculate actual offset based on (m,n,k) tile position
    uint64_t scale_offset =
        k * info->K_tile *
        VQ_CB_BYTES; // (m * info->N_iter * info->K_iter + n * info->K_iter + k) * info->vq.scale_siz e;

    flex_dma_async_1d(dst_L1_Scales, info->vq.VQ_Scale_address + scale_offset, info->vq.scale_size);
    flex_dma_async_wait_all();

    // Broadcast COLUMN-wise (like W matrix) - scales move down columns
    flex_dma_async_broadcast(dst_L1_Scales, dst_L1_Scales, info->vq.scale_size,
                             (ARCH_NUM_CLUSTER_X - 1),     // row_mask
                             info->group.wakeup_col_mask); // col_mask
    flex_dma_async_wait_all();
}

// W shape: K × N  →  Indices shape per codebook: K × (N/VQ_GROUP_SIZE)
// Loads all codebooks' indices to their separate double buffers
static inline void summa_vq_load_indices(SummaGEMMInfo* info, int buffer_idx, int m, int n, int k) {
    (void)m;
    // Use pre-computed values from setup
    uint32_t N_compressed      = info->vq.N_compressed;
    uint32_t N_tile_compressed = info->vq.N_tile_compressed;
    uint32_t tile_col_index    = n * info->summa_group_x + info->cluster_in_group_id_x;
    // Add group offset for split-N support
    uint32_t group_start = info->vq.N_group_offset_compressed + tile_col_index * N_tile_compressed;
    uint32_t row_start   = k * info->K_tile;

    // Load indices from separate arrays (one per codebook) to separate L1 buffers
    for (int cb = 0; cb < VQ_NUM_CBS; ++cb) {
        // Each codebook has its own indices array with shape (K, N/VQ_GROUP_SIZE)
        uint64_t src_offset = ((uint64_t)row_start * N_compressed + group_start) * VQ_IDX_BYTES;
        uint32_t dst_offset = (buffer_idx == 0) ? info->vq.L1_IDX1[cb] : info->vq.L1_IDX2[cb];

        flex_dma_async_2d(dst_offset, info->vq.VQ_Index_address[cb] + src_offset,
                          N_tile_compressed * VQ_IDX_BYTES, // transfer width per row
                          N_tile_compressed * VQ_IDX_BYTES, // destination stride (compact)
                          N_compressed * VQ_IDX_BYTES,      // source stride (full width)
                          info->K_tile);                    // number of rows
    }
    flex_dma_async_wait_all();

    // Broadcast all codebook indices COLUMN-wise (like W matrix) - indices move down columns
    for (int cb = 0; cb < VQ_NUM_CBS; ++cb) {
        uint32_t dst_offset = (buffer_idx == 0) ? info->vq.L1_IDX1[cb] : info->vq.L1_IDX2[cb];
        flex_dma_async_broadcast(dst_offset, dst_offset, info->vq.L1_IDX_size,
                                 (ARCH_NUM_CLUSTER_X - 1),     // row_mask
                                 info->group.wakeup_col_mask); // col_mask
    }
    flex_dma_async_wait_all();
}

static inline void summa_vq_dequantize_tile(const SummaGEMMInfo* info, uint32_t dst_L1_W, int buffer_idx,
                                            uint32_t src_L1_Scales, int k_tile) {

    // Get base addresses for indices and codebooks
    const uint8_t* idx_cb0_base =
        (const uint8_t*)(uintptr_t)((buffer_idx == 0) ? info->vq.L1_IDX1[0] : info->vq.L1_IDX2[0]);
    const uint8_t* idx_cb1_base =
        (const uint8_t*)(uintptr_t)((buffer_idx == 0) ? info->vq.L1_IDX1[1] : info->vq.L1_IDX2[1]);
    const uint16_t* cb0_base = (const uint16_t*)(uintptr_t)info->vq.L1_CB[0];
    const uint16_t* cb1_base = (const uint16_t*)(uintptr_t)info->vq.L1_CB[1];
    const uint16_t* scales   = (const uint16_t*)(uintptr_t)src_L1_Scales;

    // Keep codebook base addresses pinned to the registers the custom VLBLK instruction consumes (t0/t1)

    uint16_t* W_out           = (uint16_t*)(uintptr_t)dst_L1_W;
    const uint32_t row_length = info->vq.N_tile_compressed; // Groups per row

    for (uint16_t r = 0; r < info->K_tile; ++r) {
        // Get row-specific pointers
        const uint8_t* idx_cb0_row = idx_cb0_base + r * row_length;
        const uint8_t* idx_cb1_row = idx_cb1_base + r * row_length;
        uint16_t* W_out_row        = W_out + r * info->vq.N_tile_compressed * VQ_GROUP_SIZE;

        // Load scale for this row (1 scale per K-dimension row)
#if VQ_USE_SCALES == 1
        const uint16_t* scale_ptr = &scales[r];
        asm volatile("flh fa0, (%0)" ::"r"(scale_ptr) : "fa0", "memory");

#else
        asm volatile("fmv.h.x fa0, %0" ::"r"(0x3C00u) : "fa0"); // 1.0 in fp16
#endif

        uint32_t remaining_groups = row_length;
        uint32_t group_offset     = 0;

        while (remaining_groups > 0) {
            const uint32_t avl_elems = remaining_groups * VQ_GROUP_SIZE;
            uint32_t vl_elems        = 0;
            // fp16
            asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl_elems) : "r"(avl_elems));
            uint32_t groups_this_iter = vl_elems / VQ_GROUP_SIZE;

            if (groups_this_iter == 0u) {
                groups_this_iter = 1u;
                asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl_elems) : "r"((uint32_t)VQ_GROUP_SIZE));
            }

            const uint32_t payload_elems = groups_this_iter * VQ_GROUP_SIZE;
            uint16_t* out_ptr            = W_out_row + group_offset * VQ_GROUP_SIZE;

            asm volatile("vsetvli   zero, %4, e8,  m1, ta, ma\n"
                         "vle8.v    v0, (%0)\n"
                         "vle8.v    v1, (%1)\n"
                         "vsetvli   zero, %5, e16, m8, ta, ma\n"
                         "mv        t0, %2\n"
                         ".word     %6\n"
                         "vfmul.vf  v24, v8, fa0\n"
                         "mv        t1, %3\n"
                         ".word     %7\n"
                         "vfmacc.vf v24, fa0, v16\n"
                         "vse16.v   v24, (%8)\n"
                         :
                         : "r"(idx_cb0_row + group_offset),              // %0
                           "r"(idx_cb1_row + group_offset),              // %1
                           "r"(cb0_base),                                // %2
                           "r"(cb1_base),                                // %3
                           "r"(groups_this_iter),                        // %4
                           "r"(payload_elems),                           // %5
                           "i"(VLBLK1EI8_V(RVV_V8, RVV_V0, RVX_T0, 1)),  // %6
                           "i"(VLBLK1EI8_V(RVV_V16, RVV_V1, RVX_T1, 1)), // %7
                           "r"(out_ptr)                                  // %8
                         : "t0", "t1", "v0", "v1", "v8", "v16", "v24", "memory");

            group_offset += groups_this_iter;
            remaining_groups -= groups_this_iter;
            // if(flex_get_cluster_id()==0 && r==3){
            //     printf("\ngroups this iter %d avl %d vl %d",groups_this_iter,vl_elems,remaining_groups);
            // }
        }
    }
}
#endif

#endif //_SUMMA_DMA_H_
